// License: Apache 2.0. See LICENSE file in root directory.
// Copyright(c) 2022 Intel Corporation. All Rights Reserved.

module librealsense
{
    module dds
    {
        module topics
        {
            module raw
            {
                module device
                {
                    struct control
                    {
                        unsigned short id; // See "librealsense::dds::topics::control::msg_type"
                        unsigned long size;
                        sequence<octet> raw_data;
                    };
                };
            };
        };
    };
};
