classdef format < int64
    enumeration
        any_format      ( 0)
        z16             ( 1)
        disparity16     ( 2)
        xyz32f          ( 3)
        yuyv            ( 4)
        rgb8            ( 5)
        bgr8            ( 6)
        rgba8           ( 7)
        bgra8           ( 8)
        y8              ( 9)
        y16             (10)
        raw10           (11)
        raw16           (12)
        raw8            (13)
        uyvy            (14)
        motion_raw      (15)
        motion_xyz32f   (16)
        gpio_raw        (17)
        six_dof         (18)
        disparity32     (19)
        Y10BPack        (20)
        Distance        (21)
        mjpeg           (22)
        y8i             (23)
        y12i            (24)
        inzi            (25)
        invi            (26)
        w10             (27)
        FG              (28)
        Y411            (29)
        count           (30)
    end
end