classdef frame_metadata_value < int64
    enumeration
        frame_counter                   ( 0)
        frame_timestamp                 ( 1)
        sensor_timestamp                ( 2)
        actual_exposure                 ( 3)
        gain_level                      ( 4)
        auto_exposure                   ( 5)
        white_balance                   ( 6)
        time_of_arrival                 ( 7)
        temperature                     ( 8)
        backend_timestamp               ( 9)
        actual_fps                      (10)
        frame_laser_power               (11)
        frame_laser_power_mode          (12)
        exposure_priority               (13)
        exposure_roi_left               (14)
        exposure_roi_right              (15)
        exposure_roi_top                (16)
        exposure_roi_bottom             (17)
        brightness                      (18)
        contrast                        (19)
        saturation                      (20)
        sharpness                       (21)
        auto_white_balance_temperature  (22)
        backlight_compensation          (23)
        hue                             (24)
        gamma                           (25)
        manual_white_balance            (26)
        power_line_frequency            (27)
        low_light_compensation          (28)
        count                           (29)
    end
end