classdef option < int64
    enumeration
        backlight_compensation          ( 0)
        brightness                      ( 1)
        contrast                        ( 2)
        exposure                        ( 3)
        gain                            ( 4)
        gamma                           ( 5)
        hue                             ( 6)
        saturation                      ( 7)
        sharpness                       ( 8)
        white_balance                   ( 9)
        enable_auto_exposure            (10)
        enable_auto_white_balance       (11)
        visual_preset                   (12)
        laser_power                     (13)
        accuracy                        (14)
        motion_range                    (15)
        filter_option                   (16)
        confidence_threshold            (17)
        emitter_enabled                 (18)
        frames_queue_size               (19)
        total_frame_drops               (20)
        auto_exposure_mode              (21)
        power_line_frequency            (22)
        asic_temperature                (23)
        error_polling_enabled           (24)
        projector_temperature           (25)
        output_trigger_enabled          (26)
        motion_module_temperature       (27)
        depth_units                     (28)
        enable_motion_correction        (29)
        auto_exposure_priority          (30)
        color_scheme                    (31)
        histogram_equalization_enabled  (32)
        min_distance                    (33)
        max_distance                    (34)
        texture_source                  (35)
        filter_magnitude                (36)
        filter_smooth_alpha             (37)
        filter_smooth_delta             (38)
        holes_fill                      (39)
        stereo_baseline                 (40)
        auto_exposure_converge_step     (41)
        inter_cam_sync_mode             (42)
        count                           (43)
    end
end