// License: Apache 2.0. See LICENSE file in root directory.
// Copyright(c) 2022 Intel Corporation. All Rights Reserved.

module librealsense
{
    module dds
    {
        module topics
        {
            module raw
            {
                struct device_info
                {
                    char name[128];
                    char serial_number[32];
                    char product_line[16];
                    boolean locked;
                };
            };
            
        };
    };
};
