message(STATUS "Checking internet connection...")
file(DOWNLOAD "http://realsense-hw-public.s3-eu-west-1.amazonaws.com/Releases/connectivity_check" "${CMAKE_CURRENT_SOURCE_DIR}/connectivity_check" SHOW_PROGRESS TIMEOUT 5 STATUS status)
list (FIND status "\"No error\"" _index)
if (${_index} EQUAL -1)
    message(STATUS "Failed to identify Internet connection, disabling BUILD_WITH_TM2")
    set(BUILD_WITH_TM2 OFF)
else()
    message(STATUS "Internet connection identified, enabling BUILD_WITH_TM2")
endif()