name: build_lrs_ROS2_package

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions: read-all

jobs:

  build_lrs_ros2_package:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        ros_distribution:
          - humble
          - iron
          - rolling
          - jazzy

        include:
          # Humble Hawksbill
          - docker_image: ubuntu:jammy
            ros_distribution: humble

          # Iron Irwini
          - docker_image: ubuntu:jammy
            ros_distribution: iron

          # Rolling Ridley
          - docker_image: ubuntu:noble
            ros_distribution: rolling

          # Jazzy Jalisco
          - docker_image: ubuntu:noble
            ros_distribution: jazzy

    container:
      image: ${{ matrix.docker_image }}
    steps:

      - name: setup ROS environment
        uses: ros-tooling/setup-ros@87aeba050fd62d0ee5d5fdf4b6c9f847892ea864 #v0.7.13
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: build librealsense ROS 2
        uses: ros-tooling/action-ros-ci@1ff2c804b4c2383146d8cd8444dfda64ab4bf7ac #v0.4.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
          colcon-defaults: |  # We align the build flags to the librealsense2 ROS2 release build.
            {
              "build": {
                "cmake-args": [
                    "-DBUILD_GRAPHICAL_EXAMPLES=OFF",
                    "-DBUILD_EXAMPLES=OFF"
                ]
              }
            }
