name: build_lrs_ROS2_package

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions: read-all

jobs:

  build_lrs_ros2_package:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        ros_distribution:
          - humble
          - iron
          - rolling

        include:
          # Humble Hawksbill
          - docker_image: ubuntu:jammy
            ros_distribution: humble

          # Iron Irwini
          - docker_image: ubuntu:jammy
            ros_distribution: iron

          # Rolling Ridley
          - docker_image: ubuntu:jammy
            ros_distribution: rolling

    container:
      image: ${{ matrix.docker_image }}
    steps:

      - name: setup ROS environment
        uses: ros-tooling/setup-ros@44e00e21351330f8dbc9f298bc179cd0c7910477 # v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: build librealsense ROS 2
        uses: ros-tooling/action-ros-ci@0c87ffc035492b66c9afb9159ca9664fb0b513e1 # v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
          colcon-defaults: |  # We align the build flags to the librealsense2 ROS2 release build.
            {
              "build": {
                "cmake-args": [
                    "-DBUILD_GRAPHICAL_EXAMPLES=OFF",
                    "-DBUILD_EXAMPLES=OFF"
                ]
              }
            }
